- name: Install authorized_keys file
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', ssh_pub_key) }}"
    state: present
  when:
    - ssh_pub_key is not none
    - ssh_pub_key | length > 0
    - ssh_pub_key is file
